name: Build_and_test_project

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore workloads
        run: dotnet workload restore

      - name: Restore dependencies
        run: dotnet restore Snake.sln 

      - name: Build
        run: dotnet build Snake.sln --no-restore

      - name: Test
        run: dotnet test Snake.sln --no-build --verbosity normal
