name: Build_and_test_SnakeCore

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore workloads
        run: dotnet workload restore

      - name: Restore dependencies
        run: |
          dotnet restore SnakeCore/SnakeCore.csproj
          dotnet restore SnakeCoreTests/SnakeCoreTests.csproj

      # Build
      - name: Build projects
        run: |
          dotnet build SnakeCore/SnakeCore.csproj --no-restore
          dotnet build SnakeCoreTests/SnakeCoreTests.csproj --no-restore

      # Test
      - name: Run tests
        run: dotnet test SnakeCoreTests/SnakeCoreTests.csproj --no-build --verbosity normal
